// FBInk is licenced under the GPL3 licence

// WARNING: This file has automatically been generated on Sun, 13 Oct 2019 21:08:31 NZDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package fbink

/*
#cgo LDFLAGS: -L${SRCDIR}/../../Release -lfbink -lm
#include "../../fbink.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// FbfdAuto as defined in FBInk/fbink.h:58
	FbfdAuto = -1
)

// FontIndexT as declared in FBInk/fbink.h:94
type FontIndexT int32

// FontIndexT enumeration from FBInk/fbink.h:94
const (
	Ibm           FontIndexT = iota
	Unscii        FontIndexT = 1
	UnsciiAlt     FontIndexT = 2
	UnsciiThin    FontIndexT = 3
	UnsciiFantasy FontIndexT = 4
	UnsciiMcr     FontIndexT = 5
	UnsciiTall    FontIndexT = 6
	Block         FontIndexT = 7
	Leggie        FontIndexT = 8
	Veggie        FontIndexT = 9
	Kates         FontIndexT = 10
	Fkp           FontIndexT = 11
	Ctrld         FontIndexT = 12
	Orp           FontIndexT = 13
	Orpb          FontIndexT = 14
	Orpi          FontIndexT = 15
	Scientifica   FontIndexT = 16
	Scientificab  FontIndexT = 17
	Scientificai  FontIndexT = 18
	Terminus      FontIndexT = 19
	Terminusb     FontIndexT = 20
	Fatty         FontIndexT = 21
	Spleen        FontIndexT = 22
	Tewi          FontIndexT = 23
	Tewib         FontIndexT = 24
	Topaz         FontIndexT = 25
	Microknight   FontIndexT = 26
	Vga           FontIndexT = 27
)

// FontStyleT as declared in FBInk/fbink.h:103
type FontStyleT int32

// FontStyleT enumeration from FBInk/fbink.h:103
const (
	FntRegular    FontStyleT = iota
	FntItalic     FontStyleT = 1
	FntBold       FontStyleT = 2
	FntBoldItalic FontStyleT = 3
)

// AlignIndexT as declared in FBInk/fbink.h:111
type AlignIndexT int32

// AlignIndexT enumeration from FBInk/fbink.h:111
const (
	None   AlignIndexT = iota
	Center AlignIndexT = 1
	Edge   AlignIndexT = 2
)

// FgColorIndexT as declared in FBInk/fbink.h:133
type FgColorIndexT int32

// FgColorIndexT enumeration from FBInk/fbink.h:133
const (
	FgBlack FgColorIndexT = iota
	FgGray1 FgColorIndexT = 1
	FgGray2 FgColorIndexT = 2
	FgGray3 FgColorIndexT = 3
	FgGray4 FgColorIndexT = 4
	FgGray5 FgColorIndexT = 5
	FgGray6 FgColorIndexT = 6
	FgGray7 FgColorIndexT = 7
	FgGray8 FgColorIndexT = 8
	FgGray9 FgColorIndexT = 9
	FgGraya FgColorIndexT = 10
	FgGrayb FgColorIndexT = 11
	FgGrayc FgColorIndexT = 12
	FgGrayd FgColorIndexT = 13
	FgGraye FgColorIndexT = 14
	FgWhite FgColorIndexT = 15
)

// BgColorIndexT as declared in FBInk/fbink.h:153
type BgColorIndexT int32

// BgColorIndexT enumeration from FBInk/fbink.h:153
const (
	BgWhite BgColorIndexT = iota
	BgGraye BgColorIndexT = 1
	BgGrayd BgColorIndexT = 2
	BgGrayc BgColorIndexT = 3
	BgGrayb BgColorIndexT = 4
	BgGraya BgColorIndexT = 5
	BgGray9 BgColorIndexT = 6
	BgGray8 BgColorIndexT = 7
	BgGray7 BgColorIndexT = 8
	BgGray6 BgColorIndexT = 9
	BgGray5 BgColorIndexT = 10
	BgGray4 BgColorIndexT = 11
	BgGray3 BgColorIndexT = 12
	BgGray2 BgColorIndexT = 13
	BgGray1 BgColorIndexT = 14
	BgBlack BgColorIndexT = 15
)

// WfmModeIndexT as declared in FBInk/fbink.h:174
type WfmModeIndexT int32

// WfmModeIndexT enumeration from FBInk/fbink.h:174
const (
	WfmAuto     WfmModeIndexT = iota
	WfmDu       WfmModeIndexT = 1
	WfmGc16     WfmModeIndexT = 2
	WfmGc4      WfmModeIndexT = 3
	WfmA2       WfmModeIndexT = 4
	WfmGl16     WfmModeIndexT = 5
	WfmReagl    WfmModeIndexT = 6
	WfmReagld   WfmModeIndexT = 7
	WfmGc16Fast WfmModeIndexT = 8
	WfmGl16Fast WfmModeIndexT = 9
	WfmDu4      WfmModeIndexT = 10
	WfmGl4      WfmModeIndexT = 11
	WfmGl16Inv  WfmModeIndexT = 12
	WfmGck16    WfmModeIndexT = 13
	WfmGlkw16   WfmModeIndexT = 14
	WfmInit     WfmModeIndexT = 15
)

// HwDitherIndexT as declared in FBInk/fbink.h:184
type HwDitherIndexT int32

// HwDitherIndexT enumeration from FBInk/fbink.h:184
const (
	HwdPassthrough    HwDitherIndexT = iota
	HwdFloydSteinberg HwDitherIndexT = 1
	HwdAtkinson       HwDitherIndexT = 2
	HwdOrdered        HwDitherIndexT = 3
	HwdQuantOnly      HwDitherIndexT = 4
)

// NtxRotaIndexT as declared in FBInk/fbink.h:193
type NtxRotaIndexT int32

// NtxRotaIndexT enumeration from FBInk/fbink.h:193
const (
	NtxRotaStraight    NtxRotaIndexT = iota
	NtxRotaAllInverted NtxRotaIndexT = 1
	NtxRotaOddInverted NtxRotaIndexT = 2
	NtxRotaSane        NtxRotaIndexT = 3
)

// _CodecvtResult as declared in include/libio.h:208
type _CodecvtResult int32

// _CodecvtResult enumeration from include/libio.h:208
const ()
