// FBInk is licenced under the GPL3 licence

// WARNING: This file has automatically been generated on Sun, 13 Oct 2019 21:08:31 NZDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package fbink provides Go bindings for FBInk implementation by NiLuJe
*/
package fbink
