// FBInk is licenced under the GPL3 licence

// WARNING: This file has automatically been generated on Sun, 13 Oct 2019 21:08:31 NZDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package fbink

/*
#cgo LDFLAGS: -L${SRCDIR}/../../Release -lfbink -lm
#include "../../fbink.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Fbinkstate as declared in FBInk/fbink.h:230
type Fbinkstate struct {
	UserHz               int
	FontName             string
	ViewWidth            uint32
	ViewHeight           uint32
	ScreenWidth          uint32
	ScreenHeight         uint32
	Bpp                  uint32
	DeviceName           [16]byte
	DeviceCodename       [16]byte
	DevicePlatform       [16]byte
	DeviceId             uint16
	PenFgColor           byte
	PenBgColor           byte
	ScreenDpi            uint16
	FontW                uint16
	FontH                uint16
	MaxCols              uint16
	MaxRows              uint16
	ViewHoriOrigin       byte
	ViewVertOrigin       byte
	ViewVertOffset       byte
	FontsizeMult         byte
	GlyphWidth           byte
	GlyphHeight          byte
	IsPerfectFit         bool
	IsKoboNonMt          bool
	NtxBootRota          byte
	NtxRotaQuirk         byte
	IsNtxQuirkyLandscape bool
	CurrentRota          byte
	CanRotate            bool
	refab522f15          *C.FBInkState
	allocsab522f15       interface{}
}

// Fbinkconfig as declared in FBInk/fbink.h:275
type Fbinkconfig struct {
	Row            int16
	Col            int16
	Fontmult       byte
	Fontname       byte
	IsInverted     bool
	IsFlashing     bool
	IsCleared      bool
	IsCentered     bool
	Hoffset        int16
	Voffset        int16
	IsHalfway      bool
	IsPadded       bool
	IsRpadded      bool
	FgColor        byte
	BgColor        byte
	IsOverlay      bool
	IsBgless       bool
	IsFgless       bool
	NoViewport     bool
	IsVerbose      bool
	IsQuiet        bool
	IgnoreAlpha    bool
	Halign         byte
	Valign         byte
	ScaledWidth    int16
	ScaledHeight   int16
	WfmMode        byte
	IsDithered     bool
	SwDithering    bool
	IsNightmode    bool
	NoRefresh      bool
	ToSyslog       bool
	ref933021fe    *C.FBInkConfig
	allocs933021fe interface{}
}

// Fbinkotconfig as declared in FBInk/fbink.h:297
type Fbinkotconfig struct {
	SizePt         float32
	SizePx         uint16
	IsCentered     bool
	IsFormatted    bool
	ComputeOnly    bool
	NoTruncation   bool
	ref379abb47    *C.FBInkOTConfig
	allocs379abb47 interface{}
}

// Fbinkotfit as declared in FBInk/fbink.h:308
type Fbinkotfit struct {
	ComputedLines uint16
	RenderedLines uint16
	Truncated     bool
	ref6aee623    *C.FBInkOTFit
	allocs6aee623 interface{}
}

// Fbinkrect as declared in FBInk/fbink.h:318
type Fbinkrect struct {
	Left           uint16
	Top            uint16
	Width          uint16
	Height         uint16
	ref1b16f0cc    *C.FBInkRect
	allocs1b16f0cc interface{}
}

// Fbinkdump as declared in FBInk/fbink.h:330
type Fbinkdump struct {
	Data           []byte
	Size           uint
	Area           Fbinkrect
	Clip           Fbinkrect
	Rota           byte
	Bpp            byte
	IsFull         bool
	refebacb268    *C.FBInkDump
	allocsebacb268 interface{}
}
